name: Create Release 🚀

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: false
          DEFAULT_BUMP: patch
      - name: Create ZIP Archive
        run: |
          zip -r logseq-flow-nord-theme.zip package.json icon.png src/*
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: Release ${{ steps.create_tag.outputs.new_tag }}
          tag_name:  ${{ steps.create_tag.outputs.new_tag }}
          draft: false
          prerelease: false
          files: logseq-flow-nord-theme.zip
          repository: henices/logseq-flow-nord
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
